name: GPTFriend
main: me.egg82.gpt.GPTFriend
bootstrapper: me.egg82.gpt.BukkitBootstrap
loader: me.egg82.gpt.BukkitLoader
version: ${plugin.version}
authors: [ egg82 ]
api-version: ${paper.api.version}
description: GPT-enabled NPCs!
dependencies:
  - name: Citizens
    required: true
    bootstrap: false
  - name: PlaceholderAPI
    required: false
    bootstrap: false
  - name: UnifiedMetrics
    required: false
    bootstrap: false
  - name: squaremap
    required: false
    bootstrap: false
  - name: LuckPerms
    required: false
    bootstrap: false